import { Benefit, BenefitCategory } from '@/types/benefits';

export const BENEFIT_CATEGORIES: BenefitCategory[] = [
  {
    id: 'financial',
    label: 'Korzyści Finansowe',
    description: 'Oszczędności i korzyści ekonomiczne',
    gridCols: 'grid-cols-1 md:grid-cols-2 lg:grid-cols-3',
  },
  {
    id: 'organizational',
    label: 'Korzyści Organizacyjne',
    description: 'Usprawnienia procesów i organizacji',
    gridCols: 'grid-cols-1 md:grid-cols-2',
  },
  {
    id: 'environmental',
    label: 'Korzyści Środowiskowe',
    description: 'Pozytywny wpływ na środowisko',
    gridCols: 'grid-cols-1 md:grid-cols-2 lg:grid-cols-3',
  },
];

export const DEFAULT_BENEFITS_SETTINGS = {
  title: 'Dlaczego warto z nami współpracować?',
  subtitle:
    'Oferujemy szereg korzyści finansowych, organizacyjnych i środowiskowych dla naszych beneficjentów',
  ctaText: 'Rozpocznij współpracę',
  ctaLink: '/kontakt',
} as const;

export const BENEFITS_ANIMATION = {
  TAB_TRANSITION: 300,
  CARD_HOVER: 200,
  FADE_IN: 400,
} as const;


export const initialBenefits: Benefit[] = [

  {
    id: 1,
    title: 'Niskie oprocentowanie',
    description: 'Korzystne oprocentowanie pożyczek w stosunku do oferty bankowej',
    icon: 'DollarSign',
    category: 'financial',
    isActive: true,
    order: 1,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 2,
    title: 'Długi okres kredytowania',
    description: 'Możliwość kredytowania zadania do 15 lat',
    icon: 'Calendar',
    category: 'financial',
    isActive: true,
    order: 2,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 3,
    title: 'Karencja w spłacie',
    description: 'Możliwość karencji w spłacie kapitału do 12 miesięcy',
    icon: 'Clock',
    category: 'financial',
    isActive: true,
    order: 3,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 4,
    title: 'Brak prowizji',
    description: 'Brak prowizji za rozpatrzenie wniosku oraz aneksowania umów',
    icon: 'X',
    category: 'financial',
    isActive: true,
    order: 4,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 5,
    title: '100% finansowanie',
    description: 'Finansowanie do 100% kosztu kwalifikowanego zadania',
    icon: 'Target',
    category: 'financial',
    isActive: true,
    order: 5,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 6,
    title: 'Częściowe umorzenie',
    description: 'Możliwość umorzenia pożyczki nawet do 20% w przypadku JST',
    icon: 'TrendingDown',
    category: 'financial',
    isActive: true,
    order: 6,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  // Organizational Benefits
  {
    id: 7,
    title: 'Stabilność i wiarygodność',
    description: 'Rozpoznawalna organizacja z gwarantowaną ustawowo stabilnością finansową',
    icon: 'Building2',
    category: 'organizational',
    isActive: true,
    order: 1,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 8,
    title: 'Wieloletnie doświadczenie',
    description:
      'Bogate doświadczenie we współpracy z JST i różnymi formami organizacyjno-prawnymi',
    icon: 'Award',
    category: 'organizational',
    isActive: true,
    order: 2,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 9,
    title: 'Znajomość regionu',
    description: 'Doświadczenie w programach UE i znajomość uwarunkowań regionalnych',
    icon: 'MapPin',
    category: 'organizational',
    isActive: true,
    order: 3,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 10,
    title: 'Elastyczność',
    description: 'Dostosowanie zasad i form dofinansowania do potrzeb beneficjentów',
    icon: 'RefreshCw',
    category: 'organizational',
    isActive: true,
    order: 4,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  // Environmental Benefits
  {
    id: 11,
    title: 'Pełne wykorzystanie środków',
    description: 'Umożliwienie maksymalnego wykorzystania środków w programach rządowych',
    icon: 'Target',
    category: 'environmental',
    isActive: true,
    order: 1,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 12,
    title: 'Świadomość ekologiczna',
    description: 'Kształtowanie kompetencji ekologicznych i proekologicznych postaw społeczeństwa',
    icon: 'Leaf',
    category: 'environmental',
    isActive: true,
    order: 2,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 13,
    title: 'Zrównoważony rozwój',
    description: 'Działania służące realizacji krajowej i wojewódzkiej polityki ochrony środowiska',
    icon: 'Recycle',
    category: 'environmental',
    isActive: true,
    order: 3,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 14,
    title: 'Innowacje środowiskowe',
    description: 'Wdrażanie nowoczesnych technologii i tworzenie zielonych miejsc pracy',
    icon: 'Lightbulb',
    category: 'environmental',
    isActive: true,
    order: 4,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 15,
    title: 'Poprawa stanu środowiska',
    description: 'Wsparcie realizacji zobowiązań środowiskowych i ochrony przyrody',
    icon: 'Globe',
    category: 'environmental',
    isActive: true,
    order: 5,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 16,
    title: 'Środki europejskie',
    description: 'Pełne wykorzystanie funduszy UE na ochronę środowiska i gospodarkę wodną',
    icon: 'Flag',
    category: 'environmental',
    isActive: true,
    order: 6,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
];
