import { FileCategory, FileItem } from '@/types/file';
import { File, FileText, ImageIcon } from 'lucide-react';

export const iconMap = {
  FileText,
  ImageIcon,
  File,
};

export const defaultCategories: FileCategory[] = [
  {
    id: 'wnioski',
    title: 'Wnioski',
    icon: 'FileText',
    description: 'Formularze wniosków o dofinansowanie',
    order: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'ksiega-znaku',
    title: 'Księga znaku',
    icon: 'ImageIcon',
    description: 'Materiały dotyczące identyfikacji wizualnej',
    order: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'logotyp',
    title: 'Logotyp WFOŚiGW w Szczecinie',
    icon: 'ImageIcon',
    description: 'Pliki z logotypem w różnych formatach',
    order: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'wzory',
    title: 'Wzory',
    icon: 'FileText',
    description: 'Wzory dokumentów i formularzy',
    order: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'pomoc-publiczna',
    title: 'Załączniki dotyczące pomocy publicznej',
    icon: 'File',
    description: 'Dokumenty związane z pomocą publiczną',
    order: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'dokumenty-rozliczeniowe',
    title: 'Dokumenty rozliczeniowe',
    icon: 'FileText',
    description: 'Instrukcje i formularze rozliczeniowe',
    order: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'zalaczniki-wnioskow',
    title: 'Załączniki do wniosków',
    icon: 'File',
    description: 'Dodatkowe załączniki wymagane przy wnioskach',
    order: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'patronat',
    title: 'Patronat',
    icon: 'FileText',
    description: 'Dokumenty związane z patronatem WFOŚiGW',
    order: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const defaultFiles: FileItem[] = [
  {
    id: 'wniosek-czyste-powietrze',
    name: 'Wniosek o dofinansowanie - Program Czyste Powietrze',
    description: 'Formularz wniosku dla programu Czyste Powietrze',
    type: 'PDF',
    size: '2.3 MB',
    categoryId: 'wnioski',
    uploadedAt: '2024-01-15T00:00:00Z',
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'wniosek-moja-woda',
    name: 'Wniosek o dofinansowanie - Program Moja Woda',
    description: 'Formularz wniosku dla programu Moja Woda',
    type: 'PDF',
    size: '1.8 MB',
    categoryId: 'wnioski',
    uploadedAt: '2024-01-10T00:00:00Z',
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2024-01-10T00:00:00Z',
  },
  {
    id: 'wniosek-bezpieczny-strazak',
    name: 'Wniosek o dofinansowanie - Bezpieczny Strażak',
    description: 'Formularz wniosku dla programu Bezpieczny Strażak',
    type: 'PDF',
    size: '2.1 MB',
    categoryId: 'wnioski',
    uploadedAt: '2024-01-05T00:00:00Z',
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z',
  },
  // Księga znaku
  {
    id: 'ksiega-znaku-wfos',
    name: 'Księga znaku WFOŚiGW Szczecin',
    description: 'Kompletna księga znaku z wytycznymi użycia',
    type: 'PDF',
    size: '15.2 MB',
    categoryId: 'ksiega-znaku',
    uploadedAt: '2023-12-01T00:00:00Z',
    createdAt: '2023-12-01T00:00:00Z',
    updatedAt: '2023-12-01T00:00:00Z',
  },
  {
    id: 'wytyczne-graficzne',
    name: 'Wytyczne graficzne - krótka wersja',
    description: 'Skrócone wytyczne dotyczące identyfikacji wizualnej',
    type: 'PDF',
    size: '3.4 MB',
    categoryId: 'ksiega-znaku',
    uploadedAt: '2023-12-01T00:00:00Z',
    createdAt: '2023-12-01T00:00:00Z',
    updatedAt: '2023-12-01T00:00:00Z',
  },
  // Logotyp
  {
    id: 'logo-kolorowe-png',
    name: 'Logo WFOŚiGW - wersja kolorowa (PNG)',
    description: 'Logotyp w wersji kolorowej, format PNG',
    type: 'PNG',
    size: '1.2 MB',
    categoryId: 'logotyp',
    uploadedAt: '2023-12-01T00:00:00Z',
    createdAt: '2023-12-01T00:00:00Z',
    updatedAt: '2023-12-01T00:00:00Z',
  },
  {
    id: 'logo-kolorowe-svg',
    name: 'Logo WFOŚiGW - wersja kolorowa (SVG)',
    description: 'Logotyp w wersji kolorowej, format wektorowy',
    type: 'SVG',
    size: '245 KB',
    categoryId: 'logotyp',
    uploadedAt: '2023-12-01T00:00:00Z',
    createdAt: '2023-12-01T00:00:00Z',
    updatedAt: '2023-12-01T00:00:00Z',
  },
  {
    id: 'logo-czarnobiale-png',
    name: 'Logo WFOŚiGW - wersja czarno-biała (PNG)',
    description: 'Logotyp w wersji czarno-białej',
    type: 'PNG',
    size: '890 KB',
    categoryId: 'logotyp',
    uploadedAt: '2023-12-01T00:00:00Z',
    createdAt: '2023-12-01T00:00:00Z',
    updatedAt: '2023-12-01T00:00:00Z',
  },
  {
    id: 'logo-negatywowe-png',
    name: 'Logo WFOŚiGW - wersja negatywowa (PNG)',
    description: 'Logotyp w wersji negatywowej (białe tło)',
    type: 'PNG',
    size: '920 KB',
    categoryId: 'logotyp',
    uploadedAt: '2023-12-01T00:00:00Z',
    createdAt: '2023-12-01T00:00:00Z',
    updatedAt: '2023-12-01T00:00:00Z',
  },
  // Wzory
  {
    id: 'wzor-umowy',
    name: 'Wzór umowy o dofinansowanie',
    description: 'Standardowy wzór umowy o dofinansowanie',
    type: 'DOC',
    size: '156 KB',
    categoryId: 'wzory',
    uploadedAt: '2024-01-20T00:00:00Z',
    createdAt: '2024-01-20T00:00:00Z',
    updatedAt: '2024-01-20T00:00:00Z',
  },
  {
    id: 'wzor-sprawozdania',
    name: 'Wzór sprawozdania z realizacji projektu',
    description: 'Formularz sprawozdania końcowego',
    type: 'DOC',
    size: '234 KB',
    categoryId: 'wzory',
    uploadedAt: '2024-01-18T00:00:00Z',
    createdAt: '2024-01-18T00:00:00Z',
    updatedAt: '2024-01-18T00:00:00Z',
  },
  {
    id: 'wzor-oswiadczenia',
    name: 'Wzór oświadczenia beneficjenta',
    description: 'Oświadczenie o spełnieniu warunków programu',
    type: 'PDF',
    size: '89 KB',
    categoryId: 'wzory',
    uploadedAt: '2024-01-15T00:00:00Z',
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
];
