import { Program, ProgramCategory } from '@/types/program';

export const initialPrograms: Program[] = [
  {
    id: 1,
    name: 'Czyste Powietrze',
    description:
      'Program dofinansowania wymiany źródeł ciepła i termomodernizacji budynków mieszkalnych',
    status: 'otwarty',
    budget: '500 000 000 zł',
    deadline: '31.12.2024',
    beneficiaryCategories: ['Osoba fizyczna'],
    startDate: new Date('2023-01-01'),
    endDate: new Date('2024-12-31'),
    maxSupport: 'do 135 000 zł',
    funding: 'do 100%',
    programLink: 'https://czystepowietrze.gov.pl',
    showOnHomepage: true,
    linkedPageSlug: null,
    type: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    name: 'Moja Woda',
    description: 'Dofinansowanie systemów retencji wody deszczowej i systemów gospodarowania wodą',
    status: 'otwarty',
    budget: '100 000 000 zł',
    deadline: '30.06.2024',
    beneficiaryCategories: ['Osoba fizyczna', 'Przedsiębiorca'],
    startDate: new Date('2023-03-15'),
    endDate: new Date('2024-06-30'),
    maxSupport: 'do 6 000 zł',
    funding: 'do 80%',
    programLink: 'https://example.com/moja-woda',
    linkedPageSlug: null,
    showOnHomepage: false,
    type: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    name: 'Bezpieczny Strażak',
    description:
      'Dofinansowanie zakupu sprzętu i wyposażenia dla jednostek Ochotniczych Straży Pożarnych',
    status: 'planowany',
    budget: '50 000 000 zł',
    deadline: 'I kwartał 2025',
    beneficiaryCategories: ['Jednostka samorządu terytorialnego'],
    startDate: new Date('2025-01-01'),
    endDate: new Date('2025-12-31'),
    maxSupport: 'do 20 000 zł',
    funding: 'do 90%',
    programLink: null,
    linkedPageSlug: null,
    showOnHomepage: false,
    type: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    name: 'Zielona Energia',
    description: 'Program wsparcia instalacji odnawialnych źródeł energii dla gospodarstw domowych',
    status: 'zakończony',
    budget: '200 000 000 zł',
    deadline: 'Zakończony',
    beneficiaryCategories: ['Osoba fizyczna'],
    startDate: new Date('2022-01-01'),
    endDate: new Date('2023-12-31'),
    maxSupport: 'do 15 000 zł',
    funding: 'do 70%',
    programLink: null,
    linkedPageSlug: null,
    showOnHomepage: false,
    type: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    name: 'Ekologiczny Transport',
    description: 'Wsparcie dla zakupu pojazdów elektrycznych i hybrydowych',
    status: 'otwarty',
    budget: '150 000 000 zł',
    deadline: '30.09.2025',
    beneficiaryCategories: ['Osoba fizyczna', 'Przedsiębiorca'],
    startDate: new Date('2024-01-01'),
    endDate: new Date('2025-09-30'),
    maxSupport: 'do 25 000 zł',
    funding: 'do 60%',
    showOnHomepage: true,
    programLink: null,
    linkedPageSlug: null,
    type: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    name: 'Odnawialne Źródła',
    description: 'Program instalacji paneli fotowoltaicznych i pomp ciepła',
    status: 'planowany',
    budget: '300 000 000 zł',
    deadline: 'II kwartał 2025',
    beneficiaryCategories: ['Osoba fizyczna', 'Przedsiębiorca'],
    startDate: new Date('2025-04-01'),
    endDate: new Date('2026-03-31'),
    maxSupport: 'do 30 000 zł',
    funding: 'do 85%',
    programLink: null,
    linkedPageSlug: null,
    showOnHomepage: false,
    type: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    name: 'Termomodernizacja',
    description: 'Kompleksowa termomodernizacja budynków mieszkalnych i użyteczności publicznej',
    status: 'otwarty',
    budget: '400 000 000 zł',
    deadline: '31.12.2025',
    beneficiaryCategories: ['Osoba fizyczna', 'Jednostka samorządu terytorialnego'],
    startDate: new Date('2024-01-01'),
    endDate: new Date('2025-12-31'),
    maxSupport: 'do 40 000 zł',
    funding: 'do 75%',
    showOnHomepage: true,
    programLink: null,
    linkedPageSlug: null,
    type: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    name: 'Gospodarka Wodna',
    description: 'Modernizacja systemów wodociągowych i kanalizacyjnych',
    status: 'otwarty',
    budget: '250 000 000 zł',
    deadline: '30.06.2025',
    beneficiaryCategories: ['Jednostka samorządu terytorialnego'],
    startDate: new Date('2024-01-01'),
    endDate: new Date('2025-06-30'),
    maxSupport: 'do 12 000 zł',
    funding: 'do 80%',
    programLink: null,
    linkedPageSlug: null,
    showOnHomepage: false,
    type: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9,
    name: 'Ochrona Powietrza',
    description: 'Projekty związane z poprawą jakości powietrza i redukcją emisji',
    status: 'planowany',
    budget: '180 000 000 zł',
    deadline: 'III kwartał 2025',
    beneficiaryCategories: ['Przedsiębiorca', 'Jednostka samorządu terytorialnego'],
    startDate: new Date('2025-07-01'),
    endDate: new Date('2026-06-30'),
    maxSupport: 'do 18 000 zł',
    funding: 'do 70%',
    programLink: null,
    linkedPageSlug: null,
    showOnHomepage: false,
    type: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 10,
    name: 'Energia Słoneczna',
    description: 'Wsparcie dla instalacji fotowoltaicznych w sektorze publicznym',
    status: 'otwarty',
    budget: '120 000 000 zł',
    deadline: '31.08.2025',
    beneficiaryCategories: ['Państwowe jednostki budżetowe'],
    startDate: new Date('2024-01-01'),
    endDate: new Date('2025-08-31'),
    maxSupport: 'do 22 000 zł',
    funding: 'do 90%',
    programLink: null,
    linkedPageSlug: null,
    showOnHomepage: false,
    type: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const PROGRAM_CATEGORIES: ProgramCategory[] = [
  { id: 'all', label: 'Wszystkie' },
  { id: 'Osoba fizyczna', label: 'Mieszkańcy' },
  { id: 'Przedsiębiorca', label: 'Przedsiębiorcy' },
  { id: 'Jednostka samorządu terytorialnego', label: 'Jednostki publiczne' },
  { id: 'Państwowe jednostki budżetowe', label: 'Instytucje' },
];

export const PROGRAM_STATUS = {
  OPEN: 'otwarty',
  PLANNED: 'planowany',
  FINISHED: 'zakończony',
} as const;

export const PROGRAM_STATUS_COLORS = {
  [PROGRAM_STATUS.OPEN]: 'bg-green-100 text-green-800',
  [PROGRAM_STATUS.PLANNED]: 'bg-blue-100 text-blue-800',
  [PROGRAM_STATUS.FINISHED]: 'bg-gray-100 text-gray-800',
} as const;

export const SKELETON_ITEMS_COUNT = 6;
